//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLXE.WsSendSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSendSms.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_NMP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Add_NMP(string username, string password, string phonenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_NMP", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Add_NMPAsync(string username, string password, string phonenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove_NMP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Remove_NMP(string username, string password, string phonenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove_NMP", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Remove_NMPAsync(string username, string password, string phonenumber);
        
        // CODEGEN: Generating message contract since message sendsmsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API_QLXE.WsSendSms.sendsmsResponse sendsms(API_QLXE.WsSendSms.sendsmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendsms", ReplyAction="*")]
        System.Threading.Tasks.Task<API_QLXE.WsSendSms.sendsmsResponse> sendsmsAsync(API_QLXE.WsSendSms.sendsmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsMT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SmsMT(string user, string pass, string sdt, string infor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsMT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SmsMTAsync(string user, string pass, string sdt, string infor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSMO8x83", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SMSMO8x83(string username, string password, string phonenumber, string message, string messageid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSMO8x83", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SMSMO8x83Async(string username, string password, string phonenumber, string message, string messageid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Accstatus(string taikhoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AccstatusAsync(string taikhoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsByGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSmsByGroup(string username, string password, string groupname, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSmsByGroupAsync(string username, string password, string groupname, string message);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendsms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendsmsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public API_QLXE.WsSendSms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sdt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string infor;
        
        public sendsmsRequest() {
        }
        
        public sendsmsRequest(API_QLXE.WsSendSms.AuthHeader AuthHeader, string sdt, string infor) {
            this.AuthHeader = AuthHeader;
            this.sdt = sdt;
            this.infor = infor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendsmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendsmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sendsmsResult;
        
        public sendsmsResponse() {
        }
        
        public sendsmsResponse(string sendsmsResult) {
            this.sendsmsResult = sendsmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : API_QLXE.WsSendSms.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<API_QLXE.WsSendSms.Service1Soap>, API_QLXE.WsSendSms.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Add_NMP(string username, string password, string phonenumber) {
            return base.Channel.Add_NMP(username, password, phonenumber);
        }
        
        public System.Threading.Tasks.Task<string> Add_NMPAsync(string username, string password, string phonenumber) {
            return base.Channel.Add_NMPAsync(username, password, phonenumber);
        }
        
        public string Remove_NMP(string username, string password, string phonenumber) {
            return base.Channel.Remove_NMP(username, password, phonenumber);
        }
        
        public System.Threading.Tasks.Task<string> Remove_NMPAsync(string username, string password, string phonenumber) {
            return base.Channel.Remove_NMPAsync(username, password, phonenumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API_QLXE.WsSendSms.sendsmsResponse API_QLXE.WsSendSms.Service1Soap.sendsms(API_QLXE.WsSendSms.sendsmsRequest request) {
            return base.Channel.sendsms(request);
        }
        
        public string sendsms(API_QLXE.WsSendSms.AuthHeader AuthHeader, string sdt, string infor) {
            API_QLXE.WsSendSms.sendsmsRequest inValue = new API_QLXE.WsSendSms.sendsmsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sdt = sdt;
            inValue.infor = infor;
            API_QLXE.WsSendSms.sendsmsResponse retVal = ((API_QLXE.WsSendSms.Service1Soap)(this)).sendsms(inValue);
            return retVal.sendsmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<API_QLXE.WsSendSms.sendsmsResponse> API_QLXE.WsSendSms.Service1Soap.sendsmsAsync(API_QLXE.WsSendSms.sendsmsRequest request) {
            return base.Channel.sendsmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<API_QLXE.WsSendSms.sendsmsResponse> sendsmsAsync(API_QLXE.WsSendSms.AuthHeader AuthHeader, string sdt, string infor) {
            API_QLXE.WsSendSms.sendsmsRequest inValue = new API_QLXE.WsSendSms.sendsmsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sdt = sdt;
            inValue.infor = infor;
            return ((API_QLXE.WsSendSms.Service1Soap)(this)).sendsmsAsync(inValue);
        }
        
        public string SmsMT(string user, string pass, string sdt, string infor) {
            return base.Channel.SmsMT(user, pass, sdt, infor);
        }
        
        public System.Threading.Tasks.Task<string> SmsMTAsync(string user, string pass, string sdt, string infor) {
            return base.Channel.SmsMTAsync(user, pass, sdt, infor);
        }
        
        public int SMSMO8x83(string username, string password, string phonenumber, string message, string messageid) {
            return base.Channel.SMSMO8x83(username, password, phonenumber, message, messageid);
        }
        
        public System.Threading.Tasks.Task<int> SMSMO8x83Async(string username, string password, string phonenumber, string message, string messageid) {
            return base.Channel.SMSMO8x83Async(username, password, phonenumber, message, messageid);
        }
        
        public string Accstatus(string taikhoan) {
            return base.Channel.Accstatus(taikhoan);
        }
        
        public System.Threading.Tasks.Task<string> AccstatusAsync(string taikhoan) {
            return base.Channel.AccstatusAsync(taikhoan);
        }
        
        public string SendSmsByGroup(string username, string password, string groupname, string message) {
            return base.Channel.SendSmsByGroup(username, password, groupname, message);
        }
        
        public System.Threading.Tasks.Task<string> SendSmsByGroupAsync(string username, string password, string groupname, string message) {
            return base.Channel.SendSmsByGroupAsync(username, password, groupname, message);
        }
    }
}
